"""
Trader Aggregate - Executes a strategy for a symbol/interval.

Uses CandleBuffer internally to manage candles.
The Trader is the entry point that receives candles from the WebSocket
and generates trading signals.

Invariants:
1. ID cannot be empty
2. Symbol/Interval must match the CandleBuffer
3. Does not generate signals if the buffer is not ready (warm-up incomplete)
"""
import logging
from dataclasses import dataclass, field
from typing import List, Optional
from datetime import datetime

from ..value_objects import Symbol, Interval, Signal, Candle_static, ExecutionMode
from ..entities import Candle
from .candle_buffer import CandleBuffer
from ..strategies.base import Strategy

logger = logging.getLogger(__name__)


@dataclass
class Trader:
    """
    Aggregate that receives real-time candles and executes a strategy.
    
    Flow:
    
    1. on_candle() -> receives candles from the WebSocket
       - If is_closed=False -> updates current_candle
       - If is_closed=True -> closes the candle and generates signal
    
    The Trader does NOT duplicate CandleBuffer logic, it only orchestrates it.
    """
    id: str
    strategy: Strategy
    symbol: Symbol
    interval: Interval
    
    # Internal CandleBuffer (composition)
    _buffer: CandleBuffer = field(init=False)
    _last_signal: Signal = field(default=Signal.HOLD)
    
    def __post_init__(self) -> None:
        # Invariant 1: ID cannot be empty
        if not self.id or not self.id.strip():
            raise ValueError("Trader ID cannot be empty")
        
        # Create CandleBuffer with the same symbol/interval
        self._buffer = CandleBuffer(
            symbol=self.symbol,
            interval=self.interval,
            max_size=self.strategy.min_candles_required + 100  # Extra margin
        )
        
        logger.info(
            f"Trader '{self.id}' created: {self.symbol} {self.interval.value} "
            f"strategy={self.strategy.__class__.__name__} "
            f"min_candles={self.strategy.min_candles_required}"
        )

    # ==================
    # Core Operations
    # ==================


    def on_candle(self, candle: Candle) -> Signal:#TODO Recovery async!!!!!
        """
        Receive a candle from the WebSocket and generate signal.
        
        Args:
            candle: Candle received from stream (with is_closed True/False)
            
        Returns:
            Signal generated by the strategy
        """
        # Validate that the buffer can trade
        if not self._buffer.can_trade():
            logger.warning(f"Trader '{self.id}' in degraded mode, ignoring candle")
            return Signal.HOLD

        try:
            if candle.is_closed:
                self._buffer.on_candle_update(candle)
                self._buffer.on_candle_close(candle)

                return self._on_candle_close(candle)
            else:
                self._buffer.on_candle_update(candle)
                #Evaluacion de estrategias intrabar, no de momento.
                #self._on_tick_update(candle)
                return Signal.HOLD

        except Exception as e:
            logger.error(f"Error processing candle: {e}")
            return Signal.HOLD

    def on_candle_not_closed(self, candle: Candle) -> Signal:
        """
        Handle new candle that may close the previous one.
        """
        try:
            if self._buffer.current_candle is None:
                if self._buffer.session_origin is None:
                    self._buffer.session_origin = candle.ohlcv.timestamp
                self._buffer.on_candle_update(candle)
                return Signal.HOLD

            # Get timestamps as integers (epoch seconds)
            last_open = int(self._buffer.current_candle.ohlcv.timestamp.timestamp.timestamp())
            new_open = int(candle.ohlcv.timestamp.timestamp.timestamp())
            
            status = self._buffer._check_gap_and_alignment(
                last_open_time=last_open,
                new_open_time=new_open,
            )

            if status == "CONTINUOUS":
                # Cierre best effort: cerramos con el último estado recibido del intervalo anterior.
                candle_to_close = self._buffer.current_candle
                # Mark as closed before closing
                candle_to_close.is_closed = True
                self._buffer.on_candle_close(candle_to_close)
                self._buffer.on_candle_update(candle)
                # ON_CLOSE: Generate signal
                return self._on_candle_close(candle_to_close)

            elif status == "GAP":
                # Estado degradado, no continuar operando, backfill y resync.
                self._buffer.mark_degraded(
                    f"Gap detected: last_open={datetime.fromtimestamp(last_open)}, "
                    f"new_open={datetime.fromtimestamp(new_open)}, "
                    f"timeframe={self._buffer.timeframe_seconds}s"
                )
                logger.critical(
                    f"Trader '{self.id}' gap detected. last_open={datetime.fromtimestamp(last_open)}, "
                    f"new_open={datetime.fromtimestamp(new_open)}"
                )
                # TODO: await initiate_recovery_mode(buffer, logger)
                return Signal.HOLD

            elif status == "MISALIGNED":
                raise ValueError("Open times desalineados: posible clock drift o datos corruptos")

            else:  # OUT_OF_ORDER
                raise ValueError("Evento fuera de orden o resync")

        except ValueError as e:
            self._buffer.mark_degraded(str(e))
            logger.error(f"Trader '{self.id}' error en procesamiento de vela: {e}")
            # TODO: await initiate_recovery_mode(buffer, logger)
            return Signal.HOLD



            
    def _on_tick_update(self, candle: Candle) -> Signal:
        """
        Handle tick update (candle not yet closed).
        
        Only generates signal if strategy.execution_mode == ON_TICK.
        Otherwise just updates the buffer and returns HOLD.
        """
        self._buffer.on_candle_update(candle)
        
        # If strategy is ON_CLOSE, don't generate signal on ticks
        if self.strategy.executes_on_close:
            return Signal.HOLD
        
        # ON_TICK mode: evaluate signal on every update
        if not self.is_ready:
            return Signal.HOLD
        
        # Evaluate signal with closed candles + current candle temporarily
        closed = list(self._buffer.get_closed_candles())
        candles_for_signal = closed + [candle.static_candle]
        
        self._last_signal = self.strategy.generate_signal(candles_for_signal)
        return self._last_signal

    def _on_candle_close(self, candle: Candle) -> Signal:
        """
        Generates signal only when the candle is closed.
        """
        if not self.is_ready:
            self._last_signal = Signal.HOLD
            return Signal.HOLD
        
        # Generate signal with all closed candles
        closed = list(self._buffer.get_closed_candles())
        self._last_signal = self.strategy.generate_signal(closed)
        
        logger.debug(
            f"Trader '{self.id}' signal={self._last_signal.value} "
            f"@ {candle.ohlcv.timestamp.timestamp}"
        )
        
        return self._last_signal

    # ==================
    # Query Methods
    # ==================

    @property
    def is_ready(self) -> bool:
        """True if there are enough candles for the strategy."""
        return self._buffer.is_ready(self.strategy.min_candles_required)

    @property
    def is_degraded(self) -> bool:
        """True if the buffer is in degraded mode."""
        return self._buffer.is_degraded

    @property
    def last_signal(self) -> Signal:
        """Last generated signal."""
        return self._last_signal

    @property
    def candle_count(self) -> int:
        """Number of closed candles in the buffer."""
        return len(self._buffer)

    @property
    def execution_mode(self) -> ExecutionMode:
        """Execution mode of the strategy."""
        return self.strategy.execution_mode

    @property
    def current_candle(self) -> Optional[Candle]:
        """Current candle in construction (None if none)."""
        return self._buffer.get_current_candle()

    def get_closed_candles(self, n: Optional[int] = None) -> List[Candle_static]:
        """
        Get the last n closed candles.
        If n is None, returns all.
        """
        if n is None:
            return list(self._buffer.get_closed_candles())
        return self._buffer.last_closed(n)

    # ==================
    # Warm-up & Recovery
    # ==================

    def warm_up(self, candles: List[Candle_static]) -> None:
        """
        Initialize the buffer with historical candles.
        Called before starting real-time trading.
        
        Args:
            candles: Historical candles (must be closed, sorted by time)
        """
        self._buffer.warm_up(candles)
        logger.info(
            f"Trader '{self.id}' warmed up with {len(candles)} candles "
            f"(ready={self.is_ready})"
        )

    def recover(self, historical_candles: List[Candle_static]) -> None:
        """
        Recover the trader after an error/degradation.
        Clears the buffer and does warm-up again.
        """
        self._buffer.mark_recovered()
        self._buffer.closed_candles.clear()
        self._buffer.current_candle = None
        self.warm_up(historical_candles)
        logger.info(f"Trader '{self.id}' recovered")

    def __repr__(self) -> str:
        status = "READY" if self.is_ready else "WARMING"
        if self.is_degraded:
            status = "DEGRADED"
        return (
            f"<Trader '{self.id}' {self.symbol} {self.interval.value} "
            f"[{self.candle_count}/{self.strategy.min_candles_required}] {status}>"
        )
